// Class Lilly that implements interface Relateable
// which is used by Bubble and MergeSort
//
// David John
// October 2020


public class Lilly  implements Relateable {

    private double SeptalLength;
    private double SeptalWidth;
    private double PedalLength;
    private double PedalWidth;
    private String SpeciesName;

    // autogenerated alternate constructor
    public Lilly(double septalLength, double septalWidth, double pedalLength, double pedalWidth, String speciesName) {
        SeptalLength = septalLength;
        SeptalWidth = septalWidth;
        PedalLength = pedalLength;
        PedalWidth = pedalWidth;
        SpeciesName = speciesName;
    }

    // copy constructor
    public Lilly(Lilly other){
        this.SeptalLength = other.SeptalLength;
        this.SeptalWidth = other.SeptalWidth;
        this.PedalLength = other.PedalLength;
        this.PedalWidth = other.PedalWidth;
        this.SpeciesName = other.SpeciesName;
    }


    // this.isLessThan() as required by interface Relateable
    @Override
    public boolean isLessThan(Relateable B){
        return SeptalLength < ((Lilly)B).SeptalLength;
    }

    // this.toString() which overrides super.toString()
    @Override
    public String toString(){
        return SeptalLength + "  " + SeptalWidth;
    }
}
